name: Build Docker Images

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish frontend Docker image
      uses: docker/build-push-action@v5
      with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ["${{ github.repository }}:${{ github.sha }}", "${{ github.repository }}:latest"]
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
